insert into author(id, name, age, nationaly) values(1, 'julio', 29, 'Brasileiro')
insert into book_publisher(id, name, cnpj) values(1, 'teste ae', '123345')
insert into genre(id, name, description) values(1, 'terror papaizin', 'causa sustos')
insert into book(id, title, description, author_id, bookpublisher_id, genre_id) values(1, 'teste', 'agoraa vai', 1, 1, 1)
insert into employee(id, name, age, address, bookpublisher_id) values(1, 'zezinho', 25, 'Rua x', 1)
insert into user(id, name, age, address) values(1, 'juquinha', 21, 'Rua y')